name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch All Commits
        run: git fetch --prune --unshallow

      - name: Calculate Main Branch Commits
        id: commits
        run: echo "::set-output name=count::$(git rev-list --count origin/main)"

      - name: Update README.md
        run: |
          sed -i "s/I have worked on the main branch of my repositories `.*` times./I have worked on the main branch of my repositories `${{ steps.commits.outputs.count }}` times./" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update main branch commit count"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.SAUMITRATOKEN }}
